### ISSUE TITLE
can-import not working as expected

### ISSUE THREAD

**Issue by MarcGodard** [canjs/can-stache-ast#10]
The following should only load one styles from my understanding, however all files are being loaded no matter the variable. It did work a few times so I am assuming some sort of race condition might be going on between the vm loading and the index.stache
```
  {{#switch (scope.vm.siteStyle)}}
    {{#case ('darkly')}}
      <can-import from="~/less/darkly/styles.less"></can-import>
    {{/case}}
    {{#case ('cosmo')}}
      <can-import from="~/less/cosmo/styles.less"></can-import>
    {{/case}}
    {{#case ('yeti')}}
      <can-import from="~/less/yeti/styles.less"></can-import>
    {{/case}}
  {{/switch}}
```
<img width="386" alt="Screen Shot 2019-08-04 at 9 21 56 PM" src="https://user-images.githubusercontent.com/5016637/62432610-aa806380-b6fe-11e9-9064-6efebbe8ce35.png">

I also tried the following with the same results:

```
  {{#eq (scope.vm.siteStyle, 'darkly')}}
    <can-import from="~/less/darkly/styles.less"></can-import>
  {{/eq}}
  {{#eq (scope.vm.siteStyle, 'cosmo')}}
    <can-import from="~/less/cosmo/styles.less"></can-import>
  {{/eq}}
  {{#eq (scope.vm.siteStyle, 'yeti')}}
    <can-import from="~/less/yeti/styles.less"></can-import>
  {{/eq}}
```

**Comment by MarcGodard** [comment]
When I use a `<can-dynamic-import></can-dynamic-import>` I get this error:

(Just changing my one `<can-import>` into it, not adding the whole switch case) 

```
TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Array'
    |     index 0 -> object with constructor 'TypeError'
    --- property 'errors' closes the circle
    at JSON.stringify (<anonymous>)
    at GeneralError.FeathersError [as constructor] (/Users/marcgodard/GitHub/site-template/node_modules/@feathersjs/errors/lib/index.js:28:31)
    at new GeneralError (/Users/marcgodard/GitHub/site-template/node_modules/@feathersjs/errors/lib/index.js:170:17)
    at /Users/marcgodard/GitHub/site-template/node_modules/@feathersjs/errors/lib/error-handler.js:33:15
    at Layer.handle_error (/Users/marcgodard/GitHub/site-template/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/Users/marcgodard/GitHub/site-template/node_modules/express/lib/router/index.js:315:13)
    at /Users/marcgodard/GitHub/site-template/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/marcgodard/GitHub/site-template/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/marcgodard/GitHub/site-template/node_modules/express/lib/router/index.js:275:10)
    at Layer.handle_error (/Users/marcgodard/GitHub/site-template/node_modules/express/lib/router/layer.js:67:12)
    at trim_prefix (/Users/marcgodard/GitHub/site-template/node_modules/express/lib/router/index.js:315:13)
    at /Users/marcgodard/GitHub/site-template/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/marcgodard/GitHub/site-template/node_modules/express/lib/router/index.js:335:12)
    at SafeStream.next (/Users/marcgodard/GitHub/site-template/node_modules/express/lib/router/index.js:275:10)
    at SafeStream.emit (events.js:203:13)
    at /Users/marcgodard/GitHub/site-template/client/node_modules/done-ssr/lib/ssr-stream.js:123:10
```

What am I missing?
